export const NEW_USER = "NEW_USER";
export const FETCH_USER = "FETCH_USER";
export const USER_LOGOUT = "USER_LOGOUT";

// panel

export const FETCH_PANEL_MENU = "FETCH_PANEL_MENU";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const FETCH_MANUFACTURERS = "FETCH_MANUFACTURERS";
export const ADD_MANUFACTURER = "ADD_MANUFACTURER";
