export const NEW_USER = "NEW_USER";
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";

export const ERROR_MESSAGE = "ERROR_MESSAGE";
export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";

export const DB_ERROR = "DB_ERROR";

// panel
export const FETCH_PANEL_MENU = "FETCH_PANEL_MENU";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_MANUFACTURERS = "FETCH_MANUFACTURERS";
export const FETCH_USERS = "FETCH_USERS";

export const ADD_MENU_ITEM = "ADD_MENU_ITEM";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_MANUFACTURER = "ADD_MANUFACTURER";
export const ADD_MENU_SUBCATEGORY = "ADD_MENU_SUBCATEGORY";
export const UPLOAD_IMAGE = "UPLOAD_IMAGE";

export const DELETE_MANUFACTURER = "DELETE_MANUFACTURER";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_MENU_ITEM = "DELETE_MENU_ITEM";
export const DELETE_MENU_SUBCATEGORY = "DELETE_MENU_SUBCATEOGRY";

export const NOTIFY_SUCCESS = "NOTIFY_SUCCESS";
export const NOTIFY_ERROR = "NOTIFY_ERROR";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";

export const FILTER_PRODUCTS = "FILTER_PRODUCTS";

export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export const TOGGLE_ADMIN = "TOGGLE_ADMIN";

export const FETCH_ACTIVE_PRODUCTS = "FETCH_ACTIVE_PRODUCTS";
export const FETCH_HOT_DEALS = "FETCH_HOT_DEALS";